registry:
  restart: always
  image: registry:2
  ports:
    - 443:443
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
  volumes:
    - "${HOME}/.ssl/registry:/certs"
    - ./data:/var/lib/registry
